version: '3.7'

services:

  OEE:
    image: intersystemsdc/mining:oee-version-0.1.2
    hostname: OEE
    ports:
    - "51773:51773" # 51773 is the superserver default port
    - "52773:52773" # 52773 is the webserver/management portal port
    volumes:
    # - common_shared:/common_shared   # Shared between all spark nodes. Good place to place a file we are working with.
    - type: bind
      source: ./common_shared/
      target: /common_shared

  # DISPATCH:
  #   image: intersystemsdc/mining:dispatch-version-0.1.2
  #   hostname: DISPATCH
  #   ports:
  #   - "9003:51773" # 51773 is the superserver default port
  #   - "9004:52773" # 52773 is the webserver/management portal port

  zeppelin:
    image: intersystemsdc/irisdemo-base-zeppelin:version-1.3
    init: true
    ports:
    - "10000:9090"     # Zeppelin
    - "10001:4040"     # Zeppelin Spark UI
    volumes:
    # - common_shared:/common_shared   # The production will be looking into this folder for new PMML files
                                       # that will be sent by the zeppelin service.
    - type: bind
      source: ./common_shared/
      target: /common_shared
    - type: bind
      source: ./zeppelin/
      target: /shared

    environment:
    - IRIS_MASTER_HOST=OEE # DNS based on the name of the service!
    - IRIS_MASTER_PORT=51773 
    - IRIS_MASTER_USERNAME=SuperUser 
    - IRIS_MASTER_PASSWORD=sys 
    - IRIS_MASTER_NAMESPACE=APPINT

  sparkmaster:
    image: intersystemsdc/irisdemo-base-spark-iris:version-1.1
    hostname: sparkmaster # Must be always sparkmaster
    init: true
    environment:
      SPARK_NODE_TYPE: Master
      SPARK_PUBLIC_DNS: localhost
      IRIS_MASTER_HOST: OEE
      IRIS_MASTER_PORT: 51773
      IRIS_MASTER_USERNAME: SuperUser
      IRIS_MASTER_PASSWORD: sys
      IRIS_MASTER_NAMESPACE: APPINT
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080   # Spark Master Portal
    volumes:
    # - common_shared:/common_shared   # Shared between all spark nodes. Good place to place a file we are working with.
    - type: bind
      source: ./common_shared/
      target: /common_shared

  worker1:
    depends_on: 
      - sparkmaster
    image: intersystemsdc/irisdemo-base-spark-iris:version-1.1
    hostname: worker1
    init: true
    environment:
      IRIS_MASTER_HOST: OEE
      IRIS_MASTER_PORT: 51773
      IRIS_MASTER_USERNAME: SuperUser
      IRIS_MASTER_PASSWORD: sys
      IRIS_MASTER_NAMESPACE: APPINT

      SPARK_NODE_TYPE: Worker
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g   # You can give more memory to your work if you are getting errors when using Spark
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 8081:8081   # Spark Worker Portal
    volumes:
    # - common_shared:/common_shared   # Shared between all spark nodes. Good place to place a file we are working with.  
    - type: bind
      source: ./common_shared/
      target: /common_shared

  worker2:
    depends_on: 
      - sparkmaster
    image: intersystemsdc/irisdemo-base-spark-iris:version-1.1
    hostname: worker2
    init: true
    environment:
      IRIS_MASTER_HOST: OEE
      IRIS_MASTER_PORT: 51773
      IRIS_MASTER_USERNAME: SuperUser
      IRIS_MASTER_PASSWORD: sys
      IRIS_MASTER_NAMESPACE: APPINT

      SPARK_NODE_TYPE: Worker
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g   # You can give more memory to your work if you are getting errors when using Spark
      SPARK_WORKER_PORT: 8882
      SPARK_WORKER_WEBUI_PORT: 8082
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 8082:8082   # Spark Worker Portal
    volumes:
    # - common_shared:/common_shared   # Shared between all spark nodes. Good place to place a file we are working with.
    - type: bind
      source: ./common_shared/
      target: /common_shared